### ISSUE TITLE
Contact information not being added to groups

### ISSUE THREAD

**Issue by colicchio** [henare/gravityformssalsa#1]
How does one connect this hook to a Salsa account?

**Comment by henare** [comment]
You're testing my memory @colicchio! It's been 3 years since I worked with this.

I think the relevant part of the instructions in the readme is this:

> To get a form to submit data to Salsa, visit the add on's settings page and add the form ID to the Salsa enabled forms field.

Have you done that?

**Comment by colicchio** [comment]
Haha! Thanks for a quick response. I didn't see the settings page - where would I access that?—

**Comment by henare** [comment]
It's a Gravity Forms add-on so I guess there's a section in Gravity Forms for add-on settings.

This looks like the relevant code so the menu item is probably called "Salsa": https://github.com/henare/gravityformssalsa/blob/master/gravityformssalsa.php#L38

**Comment by colicchio** [comment]
Ah gotcha. Thanks for the help.

On Tue, May 6, 2014 at 8:53 PM, Henare Degan notifications@github.comwrote:

> It's a Gravity Forms add-on so I guess there's a section in Gravity Forms
> for add-on settings.
> 
> This looks like the relevant code so the menu item is probably called
> "Salsa":
> https://github.com/henare/gravityformssalsa/blob/master/gravityformssalsa.php#L38
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/henare/gravityformssalsa/issues/1#issuecomment-42377919
> .

## 

Mike Colicchio
CO+LAB

201 W 7th St.
Richmond, VA 23224
www.teamcolab.com
http://www.teamcolab.com/
804-433-3582 office
